removes 'feature_rds' flag
elifesciences/search pull request #278
Opened 2020-09-15 01:41 UTC by lsh-0

2020-09-15 10:44 UTC, nlisgo requested changes

2020-09-15 10:44 UTC, nlisgo commented on src/Search/Kernel.php
> -                $app['config']['feature_rds'] ? $app['config']['rds_articles'] : []
The condition needs to be removed but the parameter is still expected. I will followup with a commit.

2020-09-15 10:49 UTC, nlisgo approved these changes

2020-09-15 10:59 UTC, nlisgo commented
@lsh-0 It has been a long time since CI has been green for any PR's

I will leave you to merge this in.

2020-10-08 06:20 UTC, lsh-0 commented
> I will leave you to merge this in.

I'm more inclined to close it now to be honest.

It came up in Giorgio's PR fix, but now that RDS articles are properly integrated and are simply regular articles, do we need special handling for them in search at all? Can we just strip out all special handling of RDS articles? I can do this myself if it's the right thing to do.

2020-10-08 06:21 UTC, lsh-0 commented
> @lsh-0 It has been a long time since CI has been green for any PR's

green now

2020-10-23 12:04 UTC, merged